### ISSUE TITLE
Issue w online app

### ISSUE THREAD

**Issue by a0429** [zalo/LaplASCIIan#8]
Hiiii. I'm probably braindead, but i'm tryin 2 make this work and struggling. The online app says that [The deployment is currently unavailable INTERNAL_UNARCHIVE_FAILED], and opening the output says that the document is empty. I'm just trying to get this 2 work for a website asset (bc it's dope), but I don't have like any experience with Python. Hope you've got the time to give this a teeny look.

**Comment by zalo** [comment]
Looks like the hack I did to get it under the 50mb limit for Vercel expired since opencv-python took down the old package I was using that was smaller than that from pip.

I'll see if I can get it back, but if you did want to play with Python locally, you could install: python, `pip install opencv-python imageio pillow`, take [this file](https://github.com/zalo/LaplASCIIan/blob/master/api/index.py), delete the handler at the end and switch line 16 out for: `im = imageio.mimread(gifName, '.gif')` and call it manually...   it should return the string that makes up the animated .svg.

**Comment by a0429** [comment]
Brilliant, I'll give it a try. Thanks man : )

**Comment by zalo** [comment]
Just rebuilt the site for Google Cloud Run; should be working here: https://zalo.github.io/LaplASCIIan/

**Comment by a0429** [comment]
Omg! Thanks king : ))
